const PRODUCTS = {
  lien: [
    { id: 'lw-1', name: 'Conditional Lien Waiver — Progress Payment', desc: 'Waive lien rights conditionally upon progress payment receipt. Texas Property Code Ch. 53 statutory form.', price: 14, fmt: 'PDF', detailPage: 'lien-conditional-progress.html' },
    { id: 'lw-2', name: 'Unconditional Lien Waiver — Progress Payment', desc: 'Fully release lien rights upon progress payment. Required by most GCs before releasing funds.', price: 14, fmt: 'PDF', detailPage: 'lien-unconditional-progress.html' },
    { id: 'lw-3', name: 'Conditional Lien Waiver — Final Payment', desc: 'Conditional final payment waiver. Protects your lien rights until the check actually clears.', price: 14, fmt: 'PDF', detailPage: 'lien-conditional-final.html' },
    { id: 'lw-4', name: 'Unconditional Lien Waiver — Final Payment', desc: 'Full and final release of all lien rights upon receipt of final payment. Chapter 53 statutory form.', price: 14, fmt: 'PDF', detailPage: 'lien-unconditional-final.html' },
    { id: 'lw-5', name: "Texas Mechanic's Lien Affidavit", desc: 'Pre-formatted for county clerk filing. Enforce your right to payment on any Texas project.', price: 19, fmt: 'PDF' },
    { id: 'lw-6', name: 'Preliminary Notice / Notice to Owner', desc: 'Preserve your lien rights from day one. Should be sent before or immediately after work begins.', price: 12, fmt: 'PDF' },
    { id: 'lw-7', name: 'Lien Demand Letter', desc: 'Professional demand letter to compel payment before escalating to lien enforcement.', price: 12, fmt: 'PDF' },
    { id: 'lw-8', name: 'Notice of Commencement', desc: 'Filed by the property owner or GC to establish lien priority on the project.', price: 12, fmt: 'PDF' },
  ],
  contract: [
    { id: 'co-1', name: 'Subcontractor Agreement — General', desc: 'Comprehensive subcontractor agreement covering scope, payment terms, insurance, indemnification, and dispute resolution.', price: 29, fmt: 'PDF' },
    { id: 'co-2', name: 'Subcontractor Agreement — Labor Only', desc: 'Streamlined agreement for labor-only subcontractors. No material or equipment provisions included.', price: 19, fmt: 'PDF' },
    { id: 'co-3', name: 'Change Order Form', desc: 'Document scope changes and price adjustments with dual signature blocks. Essential for every project.', price: 12, fmt: 'PDF' },
    { id: 'co-4', name: 'Notice to Proceed', desc: 'Formal written authorization for a subcontractor to begin work on a specific project and date.', price: 9, fmt: 'PDF' },
    { id: 'co-5', name: 'Punch List Template', desc: 'Itemized project completion checklist. Track open items, assigned parties, and sign-off status.', price: 9, fmt: 'PDF' },
    { id: 'co-6', name: 'Material & Labor Invoice', desc: 'Professional invoice with line items for materials, labor, equipment, and applicable taxes.', price: 9, fmt: 'PDF' },
    { id: 'co-7', name: 'Daily Work Log / Field Report', desc: 'Document daily labor hours, materials delivered, site conditions, and visitors on your project.', price: 9, fmt: 'PDF' },
    { id: 'co-8', name: 'Subcontractor Qualification Form', desc: 'Pre-qualify subs before hiring. Verify insurance, license numbers, safety history, and references.', price: 12, fmt: 'PDF' },
  ],
  payment: [
    { id: 'pa-1', name: 'Application for Payment (Excel)', desc: 'Professional pay application with auto-calculating totals, retainage held, and net amount due.', price: 19, fmt: 'XLSX' },
    { id: 'pa-2', name: 'Schedule of Values — Continuation Sheet (Excel)', desc: 'Linked SOV that feeds directly into your pay application. Auto-calculates % complete and stored materials.', price: 19, fmt: 'XLSX' },
    { id: 'pa-3', name: 'Pay App Bundle — Application + SOV (Excel)', desc: 'Both sheets linked and auto-calculating. Tracks running balances across pay applications #1–12.', price: 39, fmt: 'XLSX' },
    { id: 'pa-4', name: 'Change Order Log (Excel)', desc: 'Track all approved and pending change orders. Auto-updates the adjusted contract sum.', price: 14, fmt: 'XLSX' },
    { id: 'pa-5', name: 'Retainage Tracker (Excel)', desc: 'Monitor retainage held, retainage released, and outstanding balance due across all pay periods.', price: 14, fmt: 'XLSX' },
    { id: 'pa-6', name: 'GC Billing Pack — All-in-One (Excel)', desc: 'Pay App + Schedule of Values + Change Order Log + Retainage Tracker — all linked and auto-calculating.', price: 59, fmt: 'XLSX' },
  ],
  safety: [
    { id: 'sf-1', name: 'OSHA 300 — Log of Work-Related Injuries & Illnesses (Excel)', desc: 'Auto-formatted Excel log with dropdown menus for injury type, body part affected, and days away from work.', price: 14, fmt: 'XLSX' },
    { id: 'sf-2', name: 'OSHA 300A — Annual Summary (Excel)', desc: 'Automatically calculates your incident rate from OSHA 300 log data. Print and post Feb 1–Apr 30.', price: 14, fmt: 'XLSX' },
    { id: 'sf-3', name: 'OSHA 301 — Injury & Illness Incident Report (Excel)', desc: 'Detailed incident report form with fillable fields, instructions tab, and OSHA submission guidance.', price: 14, fmt: 'XLSX' },
    { id: 'sf-4', name: 'OSHA Recordkeeping Bundle (Excel)', desc: 'All three OSHA forms (300, 300A, 301) in one workbook — linked, auto-calculating, with instructions.', price: 29, fmt: 'XLSX' },
    { id: 'sf-5', name: 'Toolbox Talk Log', desc: 'Document weekly safety meetings — record topics covered, trainer, attendees, and signatures.', price: 9, fmt: 'PDF' },
    { id: 'sf-6', name: 'Job Site Hazard Assessment Form', desc: 'Pre-task safety planning. Identify and document hazards before each work activity begins.', price: 9, fmt: 'PDF' },
    { id: 'sf-7', name: 'Subcontractor Safety Qualification Form', desc: 'Verify sub safety programs, EMR ratings, OSHA 300 history, and incident rates before hiring.', price: 12, fmt: 'PDF' },
  ],
};

const BUNDLES = [
  {
    id: 'b1',
    name: 'Lien Protection Pack',
    badge: 'Best for Subs',
    includes: 'All 4 lien waivers (conditional & unconditional, progress & final) + Mechanic\'s Lien Affidavit + Lien Demand Letter + Preliminary Notice',
    price: 59,
    was: 97,
  },
  {
    id: 'b2',
    name: 'New Sub Starter Pack',
    badge: 'Most Popular',
    includes: 'Subcontractor Agreement (General) + Change Order Form + Material & Labor Invoice + Lien Waiver Set (all 4) + Daily Work Log',
    price: 49,
    was: 82,
  },
  {
    id: 'b3',
    name: 'GC Operations Pack',
    badge: 'Best for GCs',
    includes: 'Sub Agreement + Sub Qualification Form + Change Order Log (Excel) + Punch List + Notice to Proceed + Pay App Bundle (Excel)',
    price: 79,
    was: 130,
  },
  {
    id: 'b4',
    name: 'OSHA Recordkeeping Bundle',
    badge: 'Safety',
    includes: 'OSHA 300 + 300A + 301 (all linked in Excel) + Toolbox Talk Log + Job Site Hazard Assessment Form',
    price: 39,
    was: 62,
  },
  {
    id: 'b5',
    name: 'Pay App Pro Bundle',
    badge: 'Billing',
    includes: 'Application for Payment + Schedule of Values + Change Order Log + Retainage Tracker — all linked in Excel with auto-calculations',
    price: 59,
    was: 92,
  },
  {
    id: 'b6',
    name: 'Texas Contractor Complete Library',
    badge: 'Best Value',
    includes: 'Every template in the vault — 50+ documents across all 4 categories. One-time purchase, lifetime access, free updates when Texas law changes.',
    price: 179,
    was: 350,
  },
];

const BLOG_POSTS = [
  {
    id: 'blog-1',
    cat: 'Lien Law',
    title: "Texas Mechanic's Lien Deadlines You Cannot Miss",
    excerpt: "Chapter 53 of the Texas Property Code has strict filing deadlines. Miss one and you lose your lien rights entirely. Here\'s a month-by-month checklist for Texas subs and suppliers.",
    date: 'Mar 28, 2025',
    read: '5 min',
    slug: 'texas-mechanics-lien-deadlines',
  },
  {
    id: 'blog-2',
    cat: 'Commercial',
    title: 'What Texas Contractors Need to Know About Retainage Law',
    excerpt: 'Texas HB 2116 capped retainage at 10% for most commercial projects. Are your contracts, subcontractor agreements, and pay apps already updated to reflect this change?',
    date: 'Mar 15, 2025',
    read: '4 min',
    slug: 'texas-retainage-law-hb2116',
  },
  {
    id: 'blog-3',
    cat: 'Contracts',
    title: '5 Clauses Every Texas Sub Agreement Must Include',
    excerpt: "A handshake deal won\'t protect you in Texas court. Make sure these five contract provisions are in every subcontractor agreement before you pick up a tool.",
    date: 'Mar 5, 2025',
    read: '6 min',
    slug: 'texas-subcontractor-agreement-clauses',
  },
  {
    id: 'blog-4',
    cat: 'Residential',
    title: 'Texas Residential Boom: What Subs Need to Know in 2025',
    excerpt: 'Austin, DFW, and Houston all hit record permit numbers. More work means more payment exposure — here\'s how to protect your cash flow on residential projects.',
    date: 'Feb 20, 2025',
    read: '4 min',
    slug: 'texas-residential-construction-2025',
  },
  {
    id: 'blog-5',
    cat: 'OSHA',
    title: 'OSHA Recordkeeping for Small Texas Contractors',
    excerpt: "Not sure if you\'re required to keep an OSHA 300 log? Here\'s exactly who must record, what qualifies as a recordable incident, and when to post your 300A annual summary.",
    date: 'Feb 8, 2025',
    read: '7 min',
    slug: 'osha-recordkeeping-small-texas-contractors',
  },
  {
    id: 'blog-6',
    cat: 'Billing',
    title: 'Why Texas Contractors Should Use an Excel Pay App',
    excerpt: 'The AIA G702/G703 PDF is the industry standard — but it\'s clunky and error-prone. A linked Excel version saves hours every billing cycle and reduces costly mistakes.',
    date: 'Jan 25, 2025',
    read: '5 min',
    slug: 'excel-pay-application-vs-aia-g702',
  },
];
